AWSTemplateFormatVersion: '2010-09-09'
Description: Continuous integration pipeline
Transform: AWS::Serverless-2016-10-31
Parameters:
  GithubOwner:
    Type: String
    Default: faboulaye
  RepositoryName:
    Type: String
    Default: elb-tuto
  BranchName:
    Type: String
    Default: develop
  Stage:
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - prod
Resources:
  ContinuousIntegration:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-pipeline
      RoleArn:
        Fn::GetAtt:
        - ContinuousIntegrationRole
        - Arn
      ArtifactStore:
        Location:
          Ref: ContinuousIntegrationArtifactStore
        Type: S3
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: 1
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            ConnectionArn:
              Fn::GetAtt:
              - GithubConnection
              - ConnectionArn
            FullRepositoryId:
              Fn::Sub: ${GithubOwner}/${RepositoryName}
            BranchName:
              Ref: BranchName
      - Name: Deploy
        Actions:
        - Name: Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: 1
            Provider: ElasticBeanstalk
          Configuration:
            ApplicationName:
              Ref: ELBTutoApplication
            EnvironmentName:
              Fn::Sub: ${Stage}-${ELBTutoApplication}
          InputArtifacts:
          - Name: SourceArtifact
          RunOrder: 1
      Tags:
      - Key: Name
        Value: Continuous Integration Pipeline
      - Key: Application
        Value: Continuous Integration
    Metadata:
      SamResourceId: ContinuousIntegration
  ContinuousIntegrationArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: continuous-integration-artifact-store
      Tags:
      - Key: Name
        Value: Continuous Integration Artifact Store
      - Key: Application
        Value: Continuous Integration
    Metadata:
      SamResourceId: ContinuousIntegrationArtifactStore
  ContinuousIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-continuous-integration-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            - s3:PutObject
            Resource:
            - Fn::GetAtt:
              - ContinuousIntegrationArtifactStore
              - Arn
            - Fn::Sub: ${ContinuousIntegrationArtifactStore.Arn}/*
          - Effect: Allow
            Action:
            - codestar-connections:UseConnection
            Resource:
            - Ref: GithubConnection
    Metadata:
      SamResourceId: ContinuousIntegrationRole
  GithubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: elb-tuto-github-connection
      ProviderType: GitHub
      Tags:
      - Key: Application
        Value: Continuous Integration
    Metadata:
      SamResourceId: GithubConnection
  ELBTutoApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: elb-tuto-application
      Description: Elastic Beanstalk Tutorial Python Sample Application
    Metadata:
      SamResourceId: ELBTutoApplication
  ELBTutoApplicationEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: ELBTutoApplication
      EnvironmentName:
        Fn::Sub: ${Stage}-${ELBTutoApplication}
      Description: AWS Elastic Beanstalk Tutorial Environment running Python Sample
        Application
      SolutionStackName: 64bit Amazon Linux 2023 v4.0.6 running Python 3.11
      CNAMEPrefix: todo
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value:
          Ref: ELBTutoApplicationInstanceProfile
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: ServiceRole
        Value:
          Ref: ELBTutoApplicationServiceRole
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: ENVIRONMENT
        Value:
          Ref: Stage
      Tags:
      - Key: Application
        Value: ELB Tuto Application
      - Key: Stage
        Value:
          Ref: Stage
    Metadata:
      SamResourceId: ELBTutoApplicationEnvironment
  ELBTutoApplicationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - elasticbeanstalk.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-service-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ec2:Describe*
            - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
            - elasticloadbalancing:Describe*
            - elasticloadbalancing:RegisterInstancesWithLoadBalancer
            - autoscaling:Describe*
            - autoscaling:UpdateAutoScalingGroup
            Resource: '*'
      Tags:
      - Key: Application
        Value: ELB Tuto Application
    Metadata:
      SamResourceId: ELBTutoApplicationServiceRole
  ELBTutoApplicationInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: ELBTutoApplicationInstanceRole
    Metadata:
      SamResourceId: ELBTutoApplicationInstanceProfile
  ELBTutoApplicationInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-instance-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}-instance-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource:
            - Fn::Sub: arn:aws:s3:::elasticbeanstalk-*-:${AWS::AccountId}
            - Fn::Sub: arn:aws:s3:::elasticbeanstalk-*-:${AWS::AccountId}/*
      Tags:
      - Key: Application
        Value: ELB Tuto Application
    Metadata:
      SamResourceId: ELBTutoApplicationInstanceRole
